import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		
		
		int counter = 0, TwoChil = 0, ThreeChil = 0, FourMoreChil = 0, CommoNum = 0;
		double RandomNum = 0,  Avg = 0;
		char FirstGender = ' ', NextGender = ' ';
		
		for (int i = 1; i <= T; i++){	
			
			RandomNum = generator.nextDouble();
			if (RandomNum > 0.5){
				FirstGender = 'b';
			} else {
				FirstGender = 'g';
			}
			NextGender = FirstGender;
			counter = 1;
			Avg ++;
		
			while (NextGender == FirstGender){
				RandomNum = generator.nextDouble();
				if (RandomNum > 0.5){
					NextGender = 'b';
				} 	else {
					NextGender = 'g';
				}
				counter ++;
				Avg ++;
			}

			if (counter == 2){
				TwoChil++;
			} else if (counter == 3){
				ThreeChil++;
			} else {
				FourMoreChil++;
			}
		}
		
		Avg = Avg/T;
		CommoNum = Math.max(TwoChil, ThreeChil);
		CommoNum = Math.max(CommoNum, FourMoreChil);
		
		System.out.println("Average: " + Avg + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + TwoChil);
		System.out.println("Number of families with 3 children: " + ThreeChil);
		System.out.println("Number of families with 4 or more children: " + FourMoreChil);
		
		if (CommoNum == FourMoreChil){
			System.out.println("The most common number of children is 4 or more.");
		} else if (CommoNum == ThreeChil){
			System.out.println("The most common number of children is 3.");
		} else {
			System.out.println("The most common number of children is 2.");
		}
	}
}
